// @import dependencies
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Box } from "@mui/material";
// @import components
import Header from "@/components/Header/Header";
// @import styling
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by Zafar ahmad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Header name="Zafar" />
          <Box sx={{ padding: "75px" }}>{children}</Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
